"use client";

import { CheckCircle2, Loader2 } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";

type Preview = { email: string; organizationName: string; organizationPosition: string; memberCategory: string; directorateName: string | null; appointAsDirector: boolean; expiresAt: string; existingAccount: boolean };

export default function HubInvitationPage() {
  const { token } = useParams<{ token: string }>();
  const [preview, setPreview] = useState<Preview | null>(null);
  const [fullName, setFullName] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState("");
  const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [accepted, setAccepted] = useState(false);
  useEffect(() => { fetch(`/api/invitations/${encodeURIComponent(token)}`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error((typeof data.error === "string" ? data.error : data.error?.message) || "Convite indisponível."); setPreview(data); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Convite indisponível.")).finally(() => setLoading(false)); }, [token]);
  async function accept(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`/api/invitations/${encodeURIComponent(token)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName, password, passwordConfirmation: confirmation }) }); const data = await response.json(); if (!response.ok) throw new Error((typeof data.error === "string" ? data.error : data.error?.message) || "Não foi possível aceitar o convite."); setAccepted(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível aceitar o convite."); } finally { setSaving(false); } }
  if (loading) return <main className="grid min-h-screen place-items-center bg-zinc-50"><Loader2 className="h-6 w-6 animate-spin" aria-label="Validando convite" /></main>;
  return <main className="grid min-h-screen place-items-center bg-zinc-50 p-5"><section className="w-full max-w-lg rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm sm:p-8">{accepted ? <div className="text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600" /><h1 className="mt-4 text-2xl font-semibold">Convite aceito</h1><p className="mt-2 text-sm text-zinc-600">Sua participação está ativa.</p><Link href="/login" className="mt-6 inline-flex rounded-xl bg-zinc-950 px-4 py-3 text-sm font-semibold text-white">Entrar no Open Impact EJ</Link></div> : preview ? <><p className="font-mono text-xs uppercase tracking-wider text-zinc-500">Convite Open Impact EJ</p><h1 className="mt-2 text-2xl font-semibold">{preview.organizationName}</h1><dl className="mt-5 grid gap-2 rounded-xl bg-zinc-50 p-4 text-sm"><div><dt className="text-zinc-500">E-mail</dt><dd className="font-medium">{preview.email}</dd></div><div><dt className="text-zinc-500">Participação</dt><dd>{preview.organizationPosition} · {preview.memberCategory}{preview.directorateName ? ` · ${preview.directorateName}` : ""}{preview.appointAsDirector ? " · liderança da Diretoria" : ""}</dd></div><div><dt className="text-zinc-500">Expira em</dt><dd>{new Date(preview.expiresAt).toLocaleString("pt-BR")}</dd></div></dl>{preview.existingAccount ? <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">Este e-mail já possui uma conta global. Entre nessa conta em outra aba e retorne para concluir o convite; sua senha existente não será alterada.</p> : null}<form onSubmit={accept} className="mt-5 space-y-4"><label className="block text-sm font-medium">Nome completo<input required value={fullName} onChange={(event) => setFullName(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-zinc-300 px-3" /></label>{!preview.existingAccount ? <><label className="block text-sm font-medium">Senha<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-zinc-300 px-3" /></label><label className="block text-sm font-medium">Confirmar senha<input required type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-zinc-300 px-3" /></label></> : null}{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}<button disabled={saving} className="w-full rounded-xl bg-zinc-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Aceitando…" : "Aceitar convite"}</button></form></> : <><h1 className="text-xl font-semibold">Convite indisponível</h1><p role="alert" className="mt-3 text-sm text-red-700">{error}</p></>}</section></main>;
}
