import { NextResponse } from "next/server";
import { formatCurrency, formatPercent } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { calculateSmallEventImpact } from "@/methodology/small-events/calculate";
import { spendingCategories } from "@/methodology/small-events/questionnaire";

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const study = await prisma.study.findUnique({
    where: { id },
    include: { responses: true },
  });

  if (!study) {
    return NextResponse.json({ error: "Study not found" }, { status: 404 });
  }

  const responses = study.responses.map((response) => ({
    ...response,
    foodSpend: Number(response.foodSpend),
    transportSpend: Number(response.transportSpend),
    shoppingSpend: Number(response.shoppingSpend),
    lodgingSpend: Number(response.lodgingSpend),
    averageStayDays: Number(response.averageStayDays),
  }));
  const result = calculateSmallEventImpact(responses);

  const categoryRows = spendingCategories
    .map(
      (category) =>
        `| ${category.label} | ${formatCurrency(result.averageByCategory[category.key] ?? 0)} | ${formatCurrency(
          result.totalByCategory[category.key] ?? 0,
        )} |`,
    )
    .join("\n");

  const markdown = `# ${study.eventName}

Generated by Open Impact EJ.

## Event

- City/state: ${study.city}/${study.state}
- Type: ${study.eventType}
- Expected audience: ${study.expectedAudience}
- Methodology: small events, direct impact only

## Results

- Total responses: ${result.totalResponses}
- Valid sample: ${result.validResponses}
- Average spend per person: ${formatCurrency(result.averageSpendPerPerson)}
- Direct impact estimate: ${formatCurrency(result.directImpactEstimate)}
- Visitor share: ${formatPercent(result.visitorShare)}

## Spending by category

| Category | Average | Total |
| --- | ---: | ---: |
${categoryRows}

## Methodological warning

These numbers are estimates. The MVP does not calculate indirect or induced impact, does not apply economic multipliers, and should be reviewed before being used in public decisions.
`;

  return new Response(markdown, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${study.eventName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-report.md"`,
    },
  });
}
