"use client";

import { useMemo, useRef, useState } from "react";

export type HubMultiSelectOption = { id: string; label: string; detail?: string };
export function HubSearchMultiSelect({ label, options, value, onChange, disabled, maxHeight = "12rem" }: { label: string; options: HubMultiSelectOption[]; value: string[]; onChange: (ids: string[]) => void; disabled?: boolean; maxHeight?: string }) {
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [active, setActive] = useState(0); const input = useRef<HTMLInputElement>(null);
  const selected = options.filter((item) => value.includes(item.id));
  const results = useMemo(() => options.filter((item) => !value.includes(item.id) && `${item.label} ${item.detail || ""}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))), [options, query, value]);
  const add = (id: string) => { if (!value.includes(id)) onChange([...value, id]); setQuery(""); setActive(0); input.current?.focus(); };
  return <fieldset disabled={disabled} className="rounded-xl border border-zinc-200 p-3"><legend className="px-1 text-sm font-medium">{label}</legend><div className="flex flex-wrap gap-1">{selected.map((item) => <span key={item.id} className="inline-flex items-center gap-1 rounded-full bg-zinc-100 px-2 py-1 text-xs">{item.label}<button type="button" aria-label={`Remover ${item.label}`} onClick={() => onChange(value.filter((id) => id !== item.id))} className="rounded hover:bg-zinc-300">×</button></span>)}</div><input ref={input} aria-label={`Buscar ${label}`} disabled={disabled} value={query} onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); setOpen(true); setActive(0); }} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setActive((index) => Math.min(index + 1, Math.max(results.length - 1, 0))); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((index) => Math.max(index - 1, 0)); } if (event.key === "Enter" && results[active]) { event.preventDefault(); add(results[active].id); } if (event.key === "Escape") setOpen(false); if (event.key === "Backspace" && !query && value.length) onChange(value.slice(0, -1)); }} className="mt-2 w-full rounded-lg border border-zinc-300 px-3 py-2 text-sm outline-none focus:border-black focus:ring-2 focus:ring-zinc-300" placeholder="Buscar e selecionar…" />{open ? <ul role="listbox" aria-label={label} style={{ maxHeight }} className="mt-2 overflow-y-auto rounded-lg border border-zinc-200 bg-white">{results.map((item, index) => <li key={item.id}><button type="button" role="option" aria-selected={false} onMouseDown={(event) => event.preventDefault()} onClick={() => add(item.id)} className={`w-full px-3 py-2 text-left text-sm ${index === active ? "bg-zinc-100" : "hover:bg-zinc-50"}`}><span className="block font-medium">{item.label}</span>{item.detail ? <span className="block text-xs text-zinc-500">{item.detail}</span> : null}</button></li>)}{!results.length ? <li className="px-3 py-2 text-sm text-zinc-500">Nenhum resultado.</li> : null}</ul> : null}</fieldset>;
}
