"use client";

import { Archive, Check, CheckCircle2, CheckSquare, Circle, Clock3, Columns3, Flag, List, Plus, RotateCcw, Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { CoreModal, Empty, ErrorNotice, coreApi, input, useCoreLoad, useCoreOptions } from "@/components/hub/HubCoreUi";
import { hubUi } from "@/components/hub/styles";

type Task = { id: string; title: string; description: string | null; status: string; priority: string; dueAt: string | null; completedAt: string | null; archivedAt: string | null; version: number; directorate: { id: string; name: string } | null; project: { id: string; title: string } | null; responsible: { id: string; name: string } | null; assignees: Array<{ member: { id: string; name: string } }>; capabilities?: { canEdit: boolean } };
const filters = [{ id: "mine", label: "Minhas tarefas" }, { id: "directorate", label: "Minha diretoria" }, { id: "all", label: "Todas" }, { id: "overdue", label: "Atrasadas" }, { id: "week", label: "Esta semana" }, { id: "completed", label: "Concluídas" }, { id: "archived", label: "Arquivadas" }] as const;
const statusLabel: Record<string, string> = { TODO: "A fazer", IN_PROGRESS: "Em andamento", BLOCKED: "Bloqueadas", DONE: "Concluídas" };

export function HubTasksPage() {
  const options = useCoreOptions(); const [filter, setFilter] = useState("mine"); const [projectId, setProjectId] = useState(""); const [search, setSearch] = useState(""); const [view, setView] = useState<"list" | "board">("list"); const [open, setOpen] = useState(false); const [form, setForm] = useState({ title: "", description: "", assigneeIds: [] as string[], directorateId: "", projectId: "", deadline: "", priority: "NORMAL" });
  const state = useCoreLoad(async () => await coreApi<{ tasks: Task[]; board: Array<{ status: string; tasks: Task[] }> }>(`/api/tasks?filter=${filter}${projectId ? `&projectId=${projectId}` : ""}`), [filter, projectId]);
  async function create(event: React.FormEvent) { event.preventDefault(); try { await coreApi("/api/tasks", { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(form) }); setOpen(false); setForm({ title: "", description: "", assigneeIds: [], directorateId: "", projectId: "", deadline: "", priority: "NORMAL" }); await state.refresh(); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Não foi possível criar."); } }
  async function move(task: Task, status: string) { try { await coreApi(`/api/tasks/${task.id}`, { method: "PATCH", body: JSON.stringify({ version: task.version, status }) }); await state.refresh(); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Não foi possível mover."); } }
  const tasks = state.data?.tasks || []; const visibleTasks = tasks.filter((task) => !search.trim() || `${task.title} ${task.description || ""} ${task.assignees.map(({ member }) => member.name).join(" ")}`.toLocaleLowerCase("pt-BR").includes(search.trim().toLocaleLowerCase("pt-BR"))); const visibleIds = new Set(visibleTasks.map(({ id }) => id)); const visibleBoard = state.data?.board.map((column) => ({ ...column, tasks: column.tasks.filter((task) => visibleIds.has(task.id)) })); const counts = { pending: tasks.filter((task) => task.status === "TODO" || task.status === "BLOCKED").length, progress: tasks.filter((task) => task.status === "IN_PROGRESS").length, done: tasks.filter((task) => task.status === "DONE").length };
  return <div className={hubUi.page}><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[11px] uppercase tracking-[.16em] text-zinc-500">Execução do trabalho</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-[-0.03em]">Tarefas</h1><p className="mt-2 text-sm text-zinc-500">Gerencie as atividades da equipe.</p></div><button onClick={() => setOpen(true)} className={hubUi.primaryButton}><Plus className="h-4 w-4" />Nova tarefa</button></header><ErrorNotice message={state.error} />
    <section className="grid gap-4 md:grid-cols-3"><Summary icon={<Circle />} label="Pendentes" value={counts.pending} tone="amber" /><Summary icon={<Clock3 />} label="Em andamento" value={counts.progress} tone="blue" /><Summary icon={<CheckCircle2 />} label="Concluídas" value={counts.done} tone="emerald" /></section>
    <section className={`${hubUi.panel} p-5`}><div className="flex flex-wrap items-center gap-3"><label className="relative min-w-[240px] flex-1"><span className="sr-only">Buscar tarefas</span><Search className="absolute left-3 top-3 h-4 w-4 text-zinc-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar tarefas..." className={`${input} pl-9`} /></label><select aria-label="Filtrar tarefas" className={`${input} sm:w-auto`} value={filter} onChange={(event) => setFilter(event.target.value)}>{filters.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}</select><select aria-label="Filtrar por projeto" className={`${input} sm:w-auto`} value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Todos os projetos</option>{options?.projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select><div className="ml-auto flex rounded-xl border border-zinc-200 bg-white p-1"><button onClick={() => setView("list")} aria-label="Lista" className={view === "list" ? `${hubUi.primaryButton} px-3` : `${hubUi.secondaryButton} border-transparent px-3`}><List className="h-4 w-4" /></button><button onClick={() => setView("board")} aria-label="Quadro" className={view === "board" ? `${hubUi.primaryButton} px-3` : `${hubUi.secondaryButton} border-transparent px-3`}><Columns3 className="h-4 w-4" /></button></div></div></section>
    {view === "list" ? <section className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visibleTasks.map((task) => <article key={task.id} className={`${hubUi.panel} min-w-0 p-5 transition hover:shadow-sm`}><div className="flex items-start justify-between"><span className="text-zinc-600">{task.status === "DONE" ? <CheckCircle2 className="h-5 w-5" /> : task.status === "IN_PROGRESS" ? <Clock3 className="h-5 w-5" /> : <Circle className="h-5 w-5" />}</span><Flag className={`h-4 w-4 ${task.priority === "URGENT" || task.priority === "HIGH" ? "text-zinc-800" : "text-zinc-400"}`} /></div><Link href={`/tarefas/${task.id}`}><h2 className="mt-4 line-clamp-2 min-h-12 font-semibold hover:underline">{task.title}</h2><p className="mt-2 line-clamp-2 min-h-10 text-sm text-zinc-500">{task.description || "Sem descrição."}</p></Link><dl className="mt-5 space-y-2 text-sm"><TaskMeta label="Responsáveis" value={assigneeNames(task)} /><TaskMeta label="Prazo" value={task.dueAt ? new Date(task.dueAt).toLocaleDateString("pt-BR") : "Sem prazo"} danger={Boolean(task.dueAt && !task.completedAt && new Date(task.dueAt) < new Date())} /><TaskMeta label="Status" value={statusLabel[task.status] || task.status} /></dl>{task.status !== "DONE" && !task.archivedAt ? <button onClick={() => void move(task, "DONE")} className="mt-4 inline-flex items-center gap-2 text-xs font-semibold"><Check className="h-4 w-4" />Marcar como concluída</button> : null}</article>)}{!visibleTasks.length && !state.loading ? <div className="md:col-span-2 lg:col-span-3"><Empty>Nenhuma tarefa neste filtro.</Empty></div> : null}</section> : <div className="grid items-start gap-4 lg:grid-cols-4">{visibleBoard?.map((column) => <section key={column.status} className="rounded-2xl bg-zinc-100 p-3"><div className="flex items-center justify-between px-1 py-2"><h2 className="text-sm font-semibold">{statusLabel[column.status] || column.status}</h2><span className="rounded-full bg-white px-2 py-0.5 text-xs">{column.tasks.length}</span></div><div className="space-y-3">{column.tasks.map((task) => <article key={task.id} className="rounded-xl border border-zinc-200 bg-white p-4 shadow-sm"><Link href={`/tarefas/${task.id}`} className="font-medium hover:underline">{task.title}</Link><p className="mt-2 text-xs text-zinc-500">{assigneeNames(task)}</p><select aria-label={`Mover ${task.title}`} className="mt-3 w-full rounded-lg border border-zinc-200 px-2 py-2 text-xs" value={task.status} onChange={(e) => void move(task, e.target.value)}>{Object.entries(statusLabel).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></article>)}</div></section>)}</div>}
    <CoreModal open={open} onClose={() => setOpen(false)} title="Nova tarefa"><form onSubmit={create} className="space-y-4"><label className="block text-sm font-medium">Título<input required className={`${input} mt-1`} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="block text-sm font-medium">Descrição<textarea className={`${input} mt-1 min-h-20`} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><AssigneePicker members={options?.members || []} selected={form.assigneeIds} onChange={(assigneeIds) => setForm({ ...form, assigneeIds })} /><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Diretoria<select className={`${input} mt-1`} value={form.directorateId} onChange={(e) => setForm({ ...form, directorateId: e.target.value })}><option value="">Toda a EJ</option>{options?.directorates.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="block text-sm font-medium">Projeto<select className={`${input} mt-1`} value={form.projectId} onChange={(e) => setForm({ ...form, projectId: e.target.value })}><option value="">Sem projeto</option>{options?.projects.map((p) => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="block text-sm font-medium">Prazo<input type="datetime-local" className={`${input} mt-1`} value={form.deadline} onChange={(e) => setForm({ ...form, deadline: e.target.value })} /></label><label className="block text-sm font-medium">Prioridade<select className={`${input} mt-1`} value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="LOW">Baixa</option><option value="NORMAL">Normal</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></select></label></div><div className="flex justify-end"><button className={hubUi.primaryButton}>Criar tarefa</button></div></form></CoreModal>
  </div>;
}

function Summary({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: number; tone: "amber" | "blue" | "emerald" }) { const tones = { amber: "bg-amber-100 text-amber-700", blue: "bg-blue-100 text-blue-700", emerald: "bg-emerald-100 text-emerald-700" }; return <div className={`${hubUi.panel} p-5`}><div className="flex items-center justify-between"><span className={`grid h-12 w-12 place-items-center rounded-xl ${tones[tone]} [&>svg]:h-6 [&>svg]:w-6`}>{icon}</span><strong className="font-display text-3xl font-semibold">{value}</strong></div><p className="mt-4 text-sm text-zinc-500">{label}</p></div>; }
function TaskMeta({ label, value, danger = false }: { label: string; value: string; danger?: boolean }) { return <div className="flex items-center justify-between gap-3"><dt className="text-zinc-500">{label}:</dt><dd className={`truncate text-right ${danger ? "font-medium text-red-700" : ""}`} title={value}>{value}</dd></div>; }
function assigneeNames(task: Task) { return task.assignees.length ? task.assignees.map(({ member }) => member.name).join(", ") : "Não definidos"; }
function AssigneePicker({ members, selected, onChange }: { members: Array<{ id: string; name: string }>; selected: string[]; onChange: (ids: string[]) => void }) { return <fieldset><legend className="text-sm font-medium">Responsáveis</legend><div className="mt-2 grid max-h-40 gap-2 overflow-y-auto rounded-xl border border-zinc-200 bg-white p-3 sm:grid-cols-2">{members.map((member) => <label key={member.id} className="flex min-h-10 items-center gap-2 rounded-lg px-2 text-sm hover:bg-zinc-50"><input type="checkbox" checked={selected.includes(member.id)} onChange={(event) => onChange(event.target.checked ? [...selected, member.id] : selected.filter((id) => id !== member.id))} />{member.name}</label>)}{!members.length ? <p className="text-sm text-zinc-500">Nenhum membro ativo disponível.</p> : null}</div></fieldset>; }

export function HubTaskDetail({ id }: { id: string }) {
  const options = useCoreOptions(); const state = useCoreLoad(async () => (await coreApi<{ task: Task }>(`/api/tasks/${id}`)).task, [id]); const [editing, setEditing] = useState(false);
  if (!state.data) return <div className={hubUi.page}>{state.error ? <ErrorNotice message={state.error} /> : <div className="h-56 animate-pulse rounded-2xl bg-white" />}</div>;
  const task = state.data;
  async function action(actionName: "archive" | "restore") { try { await coreApi(`/api/tasks/${id}`, { method: "PATCH", body: JSON.stringify({ version: task.version, action: actionName }) }); await state.refresh(); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Não foi possível atualizar."); } }
  return <div className={`${hubUi.page} max-w-5xl`}><Link href="/tarefas" className="text-sm text-zinc-500">← Tarefas</Link><header className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><CheckSquare className="h-6 w-6" /><h1 className="text-3xl font-semibold tracking-tight">{task.title}</h1></div><p className="mt-3 max-w-2xl text-sm text-zinc-600">{task.description || "Sem descrição."}</p></div>{task.capabilities?.canEdit ? <div className="flex gap-2"><button onClick={() => setEditing(true)} className={hubUi.primaryButton}>Editar</button><button onClick={() => void action(task.archivedAt ? "restore" : "archive")} className={hubUi.secondaryButton}>{task.archivedAt ? <RotateCcw className="h-4 w-4" /> : <Archive className="h-4 w-4" />}{task.archivedAt ? "Restaurar" : "Arquivar"}</button></div> : null}</header><ErrorNotice message={state.error} /><section className={`${hubUi.panel} p-5`}><dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Status" value={statusLabel[task.status] || task.status} /><Info label="Responsáveis" value={assigneeNames(task)} /><Info label="Diretoria" value={task.directorate?.name || "Toda a EJ"} /><Info label="Projeto" value={task.project?.title || "Sem projeto"} /><Info label="Prioridade" value={task.priority} /><Info label="Prazo" value={task.dueAt ? new Date(task.dueAt).toLocaleString("pt-BR") : "Não definido"} /></dl></section>
    <CoreModal open={editing} onClose={() => setEditing(false)} title="Editar tarefa"><TaskEdit task={task} options={options} onSaved={async () => { setEditing(false); await state.refresh(); }} onError={state.setError} /></CoreModal>
  </div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-zinc-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
function TaskEdit({ task, options, onSaved, onError }: { task: Task; options: ReturnType<typeof useCoreOptions>; onSaved: () => Promise<void>; onError: (value: string) => void }) { const [form, setForm] = useState({ title: task.title, description: task.description || "", assigneeIds: task.assignees.map(({ member }) => member.id), directorateId: task.directorate?.id || "", projectId: task.project?.id || "", deadline: task.dueAt ? new Date(task.dueAt).toISOString().slice(0, 16) : "", priority: task.priority, status: task.status }); async function save(event: React.FormEvent) { event.preventDefault(); try { await coreApi(`/api/tasks/${task.id}`, { method: "PATCH", body: JSON.stringify({ version: task.version, ...form, directorateId: form.directorateId || null, projectId: form.projectId || null, deadline: form.deadline || null }) }); await onSaved(); } catch (reason) { onError(reason instanceof Error ? reason.message : "Não foi possível salvar."); } } return <form onSubmit={save} className="space-y-4"><label className="block text-sm font-medium">Título<input className={`${input} mt-1`} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="block text-sm font-medium">Descrição<textarea className={`${input} mt-1 min-h-24`} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><AssigneePicker members={options?.members || []} selected={form.assigneeIds} onChange={(assigneeIds) => setForm({ ...form, assigneeIds })} /><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Status<select className={`${input} mt-1`} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{Object.entries(statusLabel).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className="block text-sm font-medium">Diretoria<select className={`${input} mt-1`} value={form.directorateId} onChange={(e) => setForm({ ...form, directorateId: e.target.value })}><option value="">Toda a EJ</option>{options?.directorates.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="block text-sm font-medium">Projeto<select className={`${input} mt-1`} value={form.projectId} onChange={(e) => setForm({ ...form, projectId: e.target.value })}><option value="">Sem projeto</option>{options?.projects.map((p) => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="block text-sm font-medium">Prazo<input type="datetime-local" className={`${input} mt-1`} value={form.deadline} onChange={(e) => setForm({ ...form, deadline: e.target.value })} /></label></div><div className="flex justify-end"><button className={hubUi.primaryButton}>Salvar</button></div></form>; }
