"use client";

import { Eye, EyeOff, Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { HUB_BRAND } from "@/lib/hub/brand";

export default function AtlasHubChangePasswordPage() {
  const router = useRouter(); const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirmation, setConfirmation] = useState(""); const [show, setShow] = useState(false); const [mustChange, setMustChange] = useState(true); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { fetch(`${HUB_BRAND.apiRoot}/me`, { cache: "no-store" }).then(async (response) => ({ response, data: await response.json() })).then(({ response, data }) => { if (!response.ok) router.replace(HUB_BRAND.loginPath); else setMustChange(data.mustChangePassword); }).catch(() => router.replace(HUB_BRAND.loginPath)); }, [router]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (next !== confirmation) { setError("As senhas não conferem."); return; } setLoading(true); try { const response = await fetch(`${HUB_BRAND.apiRoot}/auth/change-password`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword: current, newPassword: next }) }); const data = await response.json(); if (!response.ok) throw new Error((typeof data.error === "string" ? data.error : data.error?.message) || "Não foi possível alterar a senha."); router.replace(HUB_BRAND.webRoot); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Erro de conexão."); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-zinc-100 px-4 py-10"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm sm:p-8"><div className="mb-7 flex h-11 w-11 items-center justify-center rounded-xl bg-black text-sm font-bold text-white" aria-label={HUB_BRAND.productName}>{HUB_BRAND.initials}</div><h1 className="text-2xl font-semibold">Alterar senha</h1><p className="mt-2 text-sm text-zinc-600">{mustChange ? "Você precisa criar uma senha pessoal antes de continuar." : "Confirme sua senha atual e escolha uma nova."}</p>{error ? <div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div> : null}<div className="mt-6 space-y-4">{[{ id: "current", label: "Senha atual", value: current, set: setCurrent, autoComplete: "current-password" }, { id: "new", label: "Nova senha", value: next, set: setNext, autoComplete: "new-password" }, { id: "confirm", label: "Confirmar nova senha", value: confirmation, set: setConfirmation, autoComplete: "new-password" }].map((field) => <label key={field.id} className="block"><span className="mb-1.5 block text-sm font-medium">{field.label}</span><div className="relative"><input autoFocus={field.id === "current"} type={show ? "text" : "password"} autoComplete={field.autoComplete} value={field.value} onChange={(event) => field.set(event.target.value)} required minLength={field.id === "current" ? undefined : 8} className="w-full rounded-xl border border-zinc-300 px-3 py-2.5 pr-11 text-sm outline-none focus:border-black focus:ring-2 focus:ring-black/10" />{field.id === "new" ? <button type="button" onClick={() => setShow((value) => !value)} className="absolute inset-y-0 right-0 w-11 text-zinc-500" aria-label={show ? "Ocultar senhas" : "Mostrar senhas"}>{show ? <EyeOff className="mx-auto h-4 w-4" /> : <Eye className="mx-auto h-4 w-4" />}</button> : null}</div></label>)}</div><p className="mt-3 text-xs leading-5 text-zinc-500">Mínimo de 8 caracteres, com letras maiúsculas, minúsculas e número. Não use o nome do produto.</p><button disabled={loading} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-black px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : null}{loading ? "Salvando..." : "Salvar nova senha"}</button></form></main>;
}
